---

- name: Deploy enabled Services
  include_role:
    name: "service_{{ service_item }}"
  vars:
    service_domain: "{% if services[service_item].domain %}{{ services[service_item].domain }}{% else %}{{ services[service_item].subdomain }}.{{ domain }}{% endif %}"
    query: "{{ 'services.' + service_item + '.enabled|bool' }}"
    service: "{{ services[service_item] }}"
    service_root: "{{ services_root }}/{{ service_item }}"
    service_https_only: "{{ services[service_item].https_only }}"
    service_auth: "{{ services[service_item].auth }}"
    service_port: "{{ services[service_item].internal_port }}"
    service_version: "{{ lookup('vars', 'services[' + service_item + '].version', default='latest')}}"
    service_db_version: "{% if services[service_item].db_version %}{{services[service_item].db_version}}{% else %}latest{% endif %}"
    puid: "{{ PGID }}" # FIXME: service specific user and file permissions
    pgid: "{{ PUID }}" # FIXME: service specific user and file permissions
    

