---
- name: Make Fsync main directories.
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ service_root }}/data"

- name: Copy Fsync docker-compose.yml file into place.
  template:
    src: docker-compose.fsync.yml.j2
    dest: "{{ service_root }}/docker-compose.yml"
  notify: 
    - restart systemd service
 
- name: Configure Fsync systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/fsync.service
  notify: 
    - restart systemd service

- name: Enable Fsync service
  systemd:
    name: fsync
    enabled: "yes"
    daemon-reload: "yes"
