---
- name: Configure Cloud Services hosts file. You can find it at {{ traefik_root }}/cloud_hosts on your server.
  lineinfile:
    path: "{{ traefik_root }}/cloud_hosts"
    line: "{{ ansible_host }} {{ service_item }}.{{ domain }} {{ service_item }}"
  when: query
  loop: "{{ services | flatten(1) }}"
  loop_control:
    loop_var: service_item
  vars:
    query: "{{ 'services.' + service_item + '.enabled|bool' }}"


- name: Deploy enabled Services
  include_role:
    name: "deploy_service"
  when: query
  loop: "{{ services | flatten(1) }}"
  loop_control:
    loop_var: service_item
  vars:
    service_item: "{{ service_item }}"
  

- name: Ensure disabled services are not running
  systemd:
    name: "{{ service_item }}"
    state: stopped
    enable: false
  when: "not query"
  loop: "{{ services | flatten(1) }}"
  loop_control:
    loop_var: service_item
  ignore_errors: "yes"
  vars:
    query: "{{ 'services.' + service_item + '.enabled|bool' }}"