---

- name: Setup server ssh config
  vars_files: 
    - ['settings.yml', 'defaults/settings.default.yml']
    - ['vault.yml', 'defaults/vault.default.yml']
  hosts: all
  become: false
  gather_facts: false
  tags: setup_ssh
  roles:
    # Install Docker, configure basic server settings
    - provision_ssh
    #- provision_init


- name: Setup server users set
  become: true
  vars_files: 
    - ['settings.yml', 'defaults/settings.default.yml']
    - ['vault.yml', 'defaults/vault.default.yml']
    - 'vault.yml'
  hosts: main_services
  tags: setup_users
  roles:
    - provision_users


- name: Finalize server setup
  vars_files: 
    - ['settings.yml', 'defaults/settings.default.yml']
    - ['vault.yml', 'defaults/vault.default.yml']
  become: true
  hosts: main_services
  tags: setup_common
  roles:
    # Install Docker, configure basic server settings
    - provision_common
    

- name: Deploy services
  vars_files: 
    - ['settings.yml', 'defaults/settings.default.yml']
    - ['vault.yml', 'defaults/vault.default.yml']
  become: true
  hosts: main_services
  tags: setup_deploy
  roles:
    # Install Docker, configure basic server settings
    - provision_deploy


- name: Deploy services2
  vars_files: 
    - ['settings.yml', 'defaults/settings.default.yml']
    - ['vault.yml', 'defaults/vault.default.yml']
  become: true
  hosts: main_services
  tags: setup_services
  roles:
    # Install Docker, configure basic server settings
    - provision_deploy_services




