---
- name: Make Dashmachine directory.
  file:
    path: "{{ service_root }}"
    state: directory

- name: Create Dashmachine main directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - '{{ service_root }}/data'

- name: Copy Dashmachine docker-compose.yml file into place.
  template:
    src: docker-compose.dashmachine.yml.j2
    dest: "{{ service_root }}/docker-compose.yml"
  notify: 
    - restart systemd service

- name: Copy Dashmachine config.ini file into place.
  template:
    src: config.ini.j2
    dest: "{{ service_root }}/data/config.ini"
  vars:
    config_prefix: " {{ lookup('file', './settings/dashmachine/config.ini', ) }} "
    dash_services: "{{ services.keys() | list }}" 
  notify: 
    - restart systemd service

- name: Configure Dashmachine systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/dashmachine.service
  notify: 
    - restart systemd service

- name: Enable Dashmachine service 
  systemd:
    name: dashmachine
    enabled: "yes"
    daemon-reload: "yes"