---

- name: Create Cyberchef main forlder
  file:
    path: "{{ service_root }}"
    state: directory

- name: Copy Cyberchef docker-compose.yml file into place.
  template:
    src: docker-compose.cyberchef.yml.j2
    dest: "{{ service_root }}/docker-compose.yml"
  notify: 
    - restart systemd service

- name: Configure Cyberchef systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/cyberchef.service
  notify: 
    - restart systemd service


- name: Enable Cyberchef service
  systemd:
    name: "{{ service_item }}"
    enabled: "yes"
    daemon-reload: "yes"