# Timezone of the server
server_common_timezone: "Etc/UTC"


services:
  dashmachine:
    enabled: false
    name: "dashmachine"
    domain: 
    root: "{{ services_root }}/dashmachine"
    user: 
    group: 
    create_user: 
