---
- name: Make firefly_iii directory.
  file:
    path: "{{ service_root }}"
    state: directory

- name: Copy firefly_iii docker-compose.yml file into place.
  template:
    src: docker-compose.firefly_iii.yml.j2
    dest: "{{ service_root }}/docker-compose.yml"
  notify: 
    - restart systemd service

- name: Configure firefly_iii systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/firefly_iii.service
  notify: 
    - restart systemd service
    
- name: Enable firefly_iii service
  systemd:
    name: firefly_iii
    enabled: "yes"
    daemon-reload: "yes"
