---
# FIXME: too much repeats
- name: Make {{ service_item }} directory.
  file:
    path: "{{ service_root }}"
    state: directory
  
- name: Copy {{ service_item }} docker-compose.yml file into place.
  template:
    src: docker-compose.{{ service_item }}.yml.j2
    dest: "{{ service_root }}/docker-compose.yml"
  notify: 
    - restart systemd service

- name: Configure {{ service_item }} systemd service.
  template:
    src: service.j2
    dest: "/etc/systemd/system/{{ service_item }}.service"

- name: Enable {{ service_item }} service
  systemd:
    name: "{{ service_item }}"
    enabled: "yes"
    daemon-reload: "yes"
