---
- name: Make Traefik data directories.
  file:
    path: "{{ item }}"
    state: directory
    mode: "1777" # FIXME: why
  loop:
    - "{{ traefik_root }}/traefik"
    - "{{ traefik_root }}/traefik/conf.d"
    - "{{ traefik_root }}/traefik/certs"
    - /etc/docker
  ignore_errors: "yes"

- name: Configure docker log settings
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json

# Needs passlib
- name: Write user to basic auth file
  htpasswd:
    path: "{{ traefik_root }}/traefik/basicAuth"
    name: "{{ default_username }}"
    password: "{{ default_password }}"
    owner: root
    group: root
    mode: 0640

- name: Configure SSL
  file:
    path: "{{ traefik_root }}/traefik/acme.json"
    mode: 0600
    state: touch

- name: Configure Traefik systemd service.
  template:
    src: traefik.service
    dest: /etc/systemd/system/traefik.service

- name: Configure Traefik .yaml
  template:
    src: traefik.yaml.j2
    dest: "{{ traefik_root }}/traefik/traefik.yaml"

- name: Configure Traefik conf.d
  template:
    src: conf.d/middlewares.yaml
    dest: "{{ traefik_root }}/traefik/conf.d/middlewares.yaml"

- name: Copy Traefik docker-compose.yml file into place.
  template:
    src: docker-compose.traefik.yml.j2
    dest: "{{ traefik_root }}/traefik/docker-compose.yml"
  vars:
    service_domain: "{% if traefik.domain %}{{ traefik.domain }}{% else %}{{ traefik.subdomain }}.{{ domain }}{% endif %}"
    puid: "{{ PUID }}"
    pgid: "{{ PUID }}"

- name: Pull Traefik Image
  command: chdir={{ traefik_root }}/traefik/ docker-compose pull

- name: Start Traefik
  systemd:
    name: traefik
    enabled: "yes"
    daemon-reload: "yes"
    state: restarted
  ignore_errors: "yes"

- name: Deploy Authelia
  include_role:
    name: "authelia"
  vars:
    service_domain: "{{ authelia.subdomain }}.{{ domain }}"
    service_root: " {{ services_root }}/authelia"
    service_item: "authelia"


- debug:
    msg: "Main Cloud Installed successfully! Go to https://organizr.{{ domain }}/ to get started."
